### ISSUE TITLE
Test webdav add-on

### ISSUE THREAD

**Issue by lovtsovaik** [Haulmont/jmix-webdav-public#1]
CUBA doc https://doc.cuba-platform.com/webdav-2.5
CUBA demo project https://github.com/cuba-platform/webdav-demo
Jmix doc https://youtrack.haulmont.com/articles/PLAT-A-421/Jmix-WebDAV

**Comment by owlet1997** [comment]
Created test cases for WebDAV add-on:

- Load a versioned document using an entity with a WebdavDocument type field
- Loading a versioned document using an entity with a field of type WebdavDocument
- Creating a collection for documents
- Editing a document collection
- Deleting a document collection
- Navigating to a document collection using a Path string
- Loading a document larger than 20 MB
- Enabling/disabling versioning for a document
- Deleting a document
- Downloading a document from the document browser
- Download a document from a document version manager
- Editing a document through a desktop application (MS Office)
- Using digest authentication
- Downloading a document with a permission different from the main list
- Uploading multiple files at once using the FileMultiUploadField component  
- Adding a new version of a document with an entity with a field of type WebdavDocument
- Adding a new version of a document while editing an entity with the field of type WebdavDocument
- Opening a specific version of a document through a desktop application (MS Office)
- Editing a document through a desktop application (Libre Office)

**Comment by owlet1997** [comment]
List of created issues:

- https://github.com/Haulmont/jmix-webdav-public/issues/4
- https://github.com/Haulmont/jmix-webdav-public/issues/5
- https://github.com/Haulmont/jmix-webdav-public/issues/6
- https://github.com/Haulmont/jmix-webdav-public/issues/7
- https://github.com/Haulmont/jmix-webdav-public/issues/8
- https://github.com/Haulmont/jmix-webdav-public/issues/9
- https://github.com/Haulmont/jmix-webdav-public/issues/10
- https://github.com/Haulmont/jmix-webdav-public/issues/11
- https://github.com/Haulmont/jmix-webdav-public/issues/12
- https://github.com/Haulmont/jmix-webdav-public/issues/13
