### ISSUE TITLE
Property jmix.webdav.versioning isn't working in the application.properties and in the annotation

### ISSUE THREAD

**Issue by owlet1997** [Haulmont/jmix-webdav-public#14]
Environment:

**Shared steps:**
1. Open [attached](https://github.com/Haulmont/jmix-webdav-public/files/7223836/webdav-demo.zip) project -> Run app

**TC 1:**
1. Open browser at https://localhost:8443/ -> login as admin
2. Open WD's with disabled versioning browser -> Create 
3. Upload new document and set any name -> Save

**AR:**
after uploading document versioning label is displayed:
![image](https://user-images.githubusercontent.com/45730069/134631739-b60f6d52-7d1d-4e57-ac92-ef5d0eb88aea.png)
in the Document browser `Versioning` checkbox is activated:
![image](https://user-images.githubusercontent.com/45730069/134631902-0eefc554-4a93-438c-8a6d-e2cf9ea2e261.png)

**TC 2:**
1. Open WDWithDisabledVersioning.java and uncomment the annotation here:
![image](https://user-images.githubusercontent.com/45730069/134632281-cf416e1f-e4d4-4682-bbbd-6b68406e03a1.png)
2. Open the `application.properties` and comment the property `jmix.webdav.versioning`
3. Re-run app ->  browser at https://localhost:8443/ -> login as admin
4. Open WD's with disabled versioning browser -> Create 
5. Upload new document and set any name -> Save
6. Edit created instance -> Upload new document

**AR:**
 new document isn't uploaded

**Comment by glebshalyganov** [comment]
The correct property is `jmix.webdav.versioningEnabled`
