### ISSUE TITLE
It is impossible to override the default Conflict Resolution Policy

### ISSUE THREAD

**Issue by sukhova** [Haulmont/jmix-webdav-public#21]
The method described in the [Overriding Default Conflict Resolution Policy](https://doc.cuba-platform.com/webdav-2.5/?_ga=2.83181270.1576309857.1635754695-1243217318.1552655610#_overriding_default_conflict_resolution_policy) does not work in jmix

**Comment by glebshalyganov** [comment]
In order to override the default conflict resolution policy, declare a bean of `DefaultMergePolicy` type returning the needed merge policy. For example:
```java
@Bean
public DefaultMergePolicy defaultMergePolicy() {
    return RebaseMergePolicy::new;
}
```
