### ISSUE TITLE
Align roles code and name with other framework roles

### ISSUE THREAD

**Issue by gorbunkov** [Haulmont/jmix-webdav-public#3]
The role name should start with the module name followed by a semicolon, e.g.:

* UI: minimal access
* UI: edit filters
* Reports: run reports

The role code should not contain the `-role* suffix.

The role code must be put into the CODE constant.

See other roles, such as `UiMinimalRole` for examples.

**Comment by glebshalyganov** [comment]
https://github.com/Haulmont/jmix-webdav/commit/b531aff9a5f736dbfa921e84be2f69c4bee9371f
