### ISSUE TITLE
Scheduled task for cleaning expired locks is not working

### ISSUE THREAD

**Issue by owlet1997** [Haulmont/jmix-webdav-public#4]
**Environment:**
Jmix version: 1.0.1
Jmix Studio plugin version: 1.1.SNAPSHOT3512-212
IntelliJ version: IntelliJ IDEA 2021.2.1 (Community Edition)
OS: Ubuntu LTS 20.04
add-on version: 1.1.0-SNAPSHOT

**TC:**
1. Create new project -> add add-on -> run app
2. Open browser -> Upload any files -> Lock them
3. Wait more than timeout (10 minutes) -> Refresh the list

**AR:**
Locks have not been deleted:
![photo_2021-09-15_16-23-28](https://user-images.githubusercontent.com/45730069/133432647-d7442bd3-4667-4431-9134-f5ae4b8d1676.jpg)

**Comment by glebshalyganov** [comment]
This task should be run every 2 hours by default.
