### ISSUE TITLE
Unhandled exceptions if path is wrong

### ISSUE THREAD

**Issue by owlet1997** [Haulmont/jmix-webdav-public#6]
**Environment:**
Jmix version: 1.0.1
Jmix Studio plugin version: 1.1.SNAPSHOT3512-212
IntelliJ version: IntelliJ IDEA 2021.2.1 (Community Edition)
OS: Ubuntu LTS 20.04
add-on version: 1.1.0-SNAPSHOT

**Shared steps:**
1. Create new project -> add add-on -> run app
2. Open browser 

**TC 1:**
1. Clean the `Path` field -> Click `Go to path` button

**AR:**
Unexpected error:
![photo_2021-09-15_17-00-17](https://user-images.githubusercontent.com/45730069/133438134-83d77698-b7b5-4fa9-bbd2-4ac6163e709d.jpg)

**TC 2:**
1. Set any wrong value to the `Path` field -> Click `Go to path` button

**AR:**
Unexpected error:
![photo_2021-09-15_17-01-51](https://user-images.githubusercontent.com/45730069/133438286-76c4bb94-de67-4259-af09-d5910ef34d1f.jpg)

**Comment by owlet1997** [comment]
Change notification's caption to `Document collection with the given path was not found` if path is wrong

**Comment by glebshalyganov** [comment]
fixed in https://github.com/Haulmont/jmix-webdav/commit/375bd820c47beaedb710021540b4899033594048
